name: Manual SSH Session

on:
  workflow_dispatch: # 允许手动触发

jobs:
  ssh:
    runs-on: ubuntu-22.04
    timeout-minutes: 300 # 设置一个超时时间，防止忘记关闭而一直运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false # 限制只有触发此 Action 的用户可以访问
